CREATE TABLE Teams  (
	TeamID int(10) NOT NULL AUTO_INCREMENT,
    TeamName varchar(255) NOT NULL,
    City varchar(150) NOT NULL,
    PRIMARY KEY (TeamID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci; 

CREATE TABLE Games (
	GameID int(10) NOT NULL AUTO_INCREMENT,
	Host int(10) NOT NULL,
	Guest int(10) NOT NULL,
	HostGoals int(10) DEFAULT NULL,
	GuestGoals int(10) DEFAULT NULL,
	MatchDay DATETIME DEFAULT NULL,
	MatchStatus varchar(255) NOT NULL,
	PRIMARY KEY (GameID),
    FOREIGN KEY (`Guest`) REFERENCES `Teams` (`TeamID`) ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (`Host`) REFERENCES `Teams` (`TeamID`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


